[package]
name = "dumptruck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = "2.9.1"
rand = "0.8.5"
reqwest = { version = "0.11.22", features = ["blocking"] }
tokio = { version = "1.33.0", features = ["full"] }
